# make like screen and remap ctrl B to A
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# yes mouse
set -g mouse on

# true color support
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",*:RGB"

# styling
set -g status-style "bg=#333333 fg=#ea8ff2"

# status bar left: session, path, prefix indicator
set -g status-left-length 60
set -g status-left "#[fg=#333333,bg=#ea8ff2,bold] #S #[fg=#888888,bg=#333333,nobold] #{b:pane_current_path} #{?client_prefix,#[fg=#333333,bg=#97f28f,bold] PREFIX #[default],        }"

# status bar right: clock & date
set -g status-right-length 60
set -g status-right "#[fg=#888888] %a %H:%M:%S #[fg=#333333,bg=#ea8ff2,bold] %d-%b-%Y "

# center window list - this is a bit wonky, might reconsider
set -g status-justify centre

# window list
set -g window-status-separator ""
setw -g window-status-format "#[fg=#888888,bg=#333333] #I:#W "
setw -g window-status-current-format "#[fg=#333333,bg=#ea8ff2,bold] #I:#W "
setw -g window-status-activity-style "fg=#ffffff,bold"

set -g status-interval 1
set -g message-style "bg=#333333 fg=#ea8ff2"

# reduce esc delay
set -sg escape-time 0

# send focus events to apps inside panes
set -g focus-events on

# increase scrollback buffer size
set -g history-limit 50000

# start windows and panes from 1
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on

# navigation with vim keys
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# pane resizing with vim keys
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# vi copy mode
setw -g mode-keys vi

# vi-style copy mode
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
if-shell "uname | grep -q Darwin" \
    "bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'pbcopy'" \
    "bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'wl-copy && wl-copy --primary'"

# open new panes in current directory
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# R to reload conf
bind-key R source-file ~/.tmux.conf \; display "Config reloaded!"
