# make like screen and remap ctrl B to A
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# set mouse scrolling on for mental health reasons
set -g mouse on

# true color support
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

# reduce esc delay
set -sg escape-time 0

# increase scrollback buffer size
set -g history-limit 50000

# start windows and panes from 1
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on

# navigation with vim keys
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# vi copy mode
setw -g mode-keys vi

# vi-style copy mode
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
if-shell "uname | grep -q Darwin" \
    "bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'pbcopy'" \
    "bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'wl-copy && wl-copy --primary'"

# open new panes in current directory
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# R to reload conf
bind-key R source-file ~/.tmux.conf \; display "Config reloaded!"
